default_questions = {
    'Spelling': {
        'Easy': [
            ("Cat", "Cat"),
            ("Dog", "Dog"),
            ("Sun", "Sun"),
            ("Moon", "Moon"),
            ("Tree", "Tree"),
            ("Book", "Book"),
            ("Car", "Car"),
            ("Fish", "Fish"),
            ("Bird", "Bird"),
            ("House", "House"),
        ],
        'Intermediate': [
            ("Mountain", "Mountain"),
            ("Beautiful", "Beautiful"),
            ("Elephant", "Elephant"),
            ("Incredible", "Incredible"),
            ("Journey", "Journey"),
            ("Knowledge", "Knowledge"),
            ("Library", "Library"),
            ("Mystery", "Mystery"),
            ("Nature", "Nature"),
            ("Original", "Original"),
        ],
        'Advanced': [
            ("Accommodate", "Accommodate"),
            ("Conscientious", "Conscientious"),
            ("Unnecessary", "Unnecessary"),
            ("Embarrassment", "Embarrassment"),
            ("Millennium", "Millennium"),
            ("Perseverance", "Perseverance"),
            ("Superintendent", "Superintendent"),
            ("Phenomenon", "Phenomenon"),
            ("Rhythm", "Rhythm"),
            ("Liquefy", "Liquefy"),
        ],
    },
    'MathArithmetic': {
        'Beginner': [
            ("What is 2 + 2?", "4"),
            ("What is 3 + 5?", "8"),
            ("What is 7 - 4?", "3"),
            ("What is 6 x 1?", "6"),
            ("What is 9 / 3?", "3"),
            ("What is 5 + 2?", "7"),
            ("What is 8 - 6?", "2"),
            ("What is 4 x 2?", "8"),
            ("What is 10 / 2?", "5"),
            ("What is 1 + 1?", "2"),
        ],
        'Intermediate': [
            ("What is 12 x 12?", "144"),
            ("What is 15 / 3?", "5"),
            ("What is 50 - 25?", "25"),
            ("What is 8 x 7?", "56"),
            ("What is 36 / 6?", "6"),
            ("What is 14 + 28?", "42"),
            ("What is 100 - 55?", "45"),
            ("What is 9 x 9?", "81"),
            ("What is 20 / 4?", "5"),
            ("What is 40 + 60?", "100"),
        ],
        'Advanced': [
            ("What is the square root of 144?", "12"),
            ("What is 123 x 3?", "369"),
            ("What is 1000 / 25?", "40"),
            ("What is 58 + 77?", "135"),
            ("What is 200 - 123?", "77"),
            ("What is 49 x 2?", "98"),
            ("What is 500 / 5?", "100"),
            ("What is 33 + 66?", "99"),
            ("What is 150 - 75?", "75"),
            ("What is the square root of 121?", "11"),
        ],
    },
    # Add other skills and levels as needed
}