default_questions = {
    'Spelling': {
        'Easy': [
            ("Cat", "Cat"),
            ("Dog", "Dog"),
            ("Sun", "Sun"),
            ("Moon", "Moon"),
            ("Tree", "Tree"),
            ("Book", "Book"),
            ("Car", "Car"),
            ("Fish", "Fish"),
            ("Bird", "Bird"),
            ("House", "House"),
            ("Ball", "Ball"),
            ("Chair", "Chair"),
            ("Door", "Door"),
            ("Window", "Window"),
            ("School", "School"),
            ("Plant", "Plant"),
            ("Food", "Food"),
            ("Water", "Water"),
            ("Table", "Table"),
            ("Mouse", "Mouse"),
            ("Shoe", "Shoe"),
            ("Ship", "Ship"),
            ("Train", "Train"),
            ("Road", "Road"),
            ("Garden", "Garden"),
        ],
        'Intermediate': [
            ("Mountain", "Mountain"),
            ("Beautiful", "Beautiful"),
            ("Elephant", "Elephant"),
            ("Incredible", "Incredible"),
            ("Journey", "Journey"),
            ("Knowledge", "Knowledge"),
            ("Library", "Library"),
            ("Mystery", "Mystery"),
            ("Nature", "Nature"),
            ("Original", "Original"),
            ("Adventure", "Adventure"),
            ("Challenge", "Challenge"),
            ("Delicious", "Delicious"),
            ("Extraordinary", "Extraordinary"),
            ("Fascinating", "Fascinating"),
            ("Generosity", "Generosity"),
            ("Harmonious", "Harmonious"),
            ("Imagination", "Imagination"),
            ("Jubilation", "Jubilation"),
            ("Kaleidoscope", "Kaleidoscope"),
            ("Luminous", "Luminous"),
            ("Magnificent", "Magnificent"),
            ("Nostalgia", "Nostalgia"),
            ("Opportunity", "Opportunity"),
            ("Picturesque", "Picturesque"),
        ],
        'Advanced': [
            ("Accommodate", "Accommodate"),
            ("Conscientious", "Conscientious"),
            ("Unnecessary", "Unnecessary"),
            ("Embarrassment", "Embarrassment"),
            ("Millennium", "Millennium"),
            ("Perseverance", "Perseverance"),
            ("Superintendent", "Superintendent"),
            ("Phenomenon", "Phenomenon"),
            ("Rhythm", "Rhythm"),
            ("Liquefy", "Liquefy"),
            ("Subterranean", "Subterranean"),
            ("Quintessential", "Quintessential"),
            ("Mischievous", "Mischievous"),
            ("Idiosyncrasy", "Idiosyncrasy"),
            ("Exhilarate", "Exhilarate"),
            ("Dichotomy", "Dichotomy"),
            ("Bureaucracy", "Bureaucracy"),
            ("Antithesis", "Antithesis"),
            ("Onomatopoeia", "Onomatopoeia"),
            ("Pernicious", "Pernicious"),
            ("Synecdoche", "Synecdoche"),
            ("Euphemism", "Euphemism"),
            ("Protagonist", "Protagonist"),
            ("Hyperbole", "Hyperbole"),
            ("Oxymoron", "Oxymoron")
        ]
    },
    'Grammar': {
        'Easy': [
            ("She don't like apples.", "She doesn't like apples."),
            ("Him went to the store.", "He went to the store."),
            ("I has two cats.", "I have two cats."),
            ("You was at the park.", "You were at the park."),
            ("They is coming to the movie.", "They are coming to the movie."),
            ("Me and my friend likes to swim.", "My friend and I like to swim."),
            ("He do not have a pencil.", "He does not have a pencil."),
            ("We was happy to see her.", "We were happy to see her."),
            ("She have a big house.", "She has a big house."),
            ("Him and I seen a movie.", "He and I saw a movie."),
            ("We goes to gym every day.", "We go to the gym every day."),
            ("They was late to the meeting.", "They were late to the meeting."),
            ("Him is my best friend.", "He is my best friend."),
            ("Her have a red car.", "She has a red car."),
            ("I can sings well.", "I can sing well."),
            ("You runs fast.", "You run fast."),
            ("Them are playing soccer.", "They are playing soccer."),
            ("It don't matter.", "It doesn't matter."),
            ("My brother like fishing.", "My brother likes fishing."),
            ("She and him is going on a trip.", "She and he are going on a trip."),
            ("I am taller than her.", "I am taller than she."),
            ("He do his homework.", "He does his homework."),
            ("They eats dinner at 8 PM.", "They eat dinner at 8 PM."),
            ("We was going to the market.", "We were going to the market."),
        ],
        'Intermediate': [
            ("Me and John is going out.", "John and I are going out."),
            ("There's many reasons to be happy.", "There are many reasons to be happy."),
            ("Each of the dogs have a collar.", "Each of the dogs has a collar."),
            ("Neither of the answers is correct.", "Neither of the answers are correct."),
            ("Me and her were at the party.", "She and I were at the party."),
            ("The team play very well together.", "The team plays very well together."),
            ("Who do you think will win?", "Whom do you think will win?"),
            ("Between you and I, this is confidential.", "Between you and me, this is confidential."),
            ("The data is showing a clear trend.", "The data are showing a clear trend."),
            ("Each students have their own locker.", "Each student has his or her own locker."),
            ("Who should I give this to?", "To whom should I give this?"),
            ("The group of students was loud.", "The group of students were loud."),
            ("Me and my friends seen a movie.", "My friends and I saw a movie."),
            ("Her and me went shopping.", "She and I went shopping."),
            ("I ain't got no money.", "I don't have any money."),
            ("He done the work.", "He did the work."),
            ("Her and I is friends.", "She and I are friends."),
            ("I should of called you.", "I should have called you."),
            ("Who's bag is this?", "Whose bag is this?"),
            ("Me and her is planning a party.", "She and I are planning a party."),
            ("I didn't do nothing.", "I didn't do anything."),
            ("There's too many people here.", "There are too many people here."),
            ("He don't never listen.", "He never listens."),
            ("It's five persons in the room.", "There are five people in the room."),
        ],
        'Advanced': [
            ("Whom is responsible for this mess?", "Who is responsible for this mess?"),
            ("The committee have made its decision.", "The committee has made its decision."),
            ("Its a beautiful day outside.", "It's a beautiful day outside."),
            ("Her and I went shopping together.", "She and I went shopping together."),
            ("He don't know where he's going.", "He doesn't know where he's going."),
            ("There's several issues to discuss.", "There are several issues to discuss."),
            ("Me and him should work together.", "He and I should work together."),
            ("Her singing beautifully, the audience applauded.",
             "Singing beautifully, she was applauded by the audience."),
            ("The group of students are walking to school.", "The group of students is walking to school."),
            ("One of the boy's hats is black.", "One of the boys' hats is black."),
            ("I would have went if I knew.", "I would have gone if I had known."),
            ("If I would have known, I would have went.", "If I had known, I would have gone."),
            ("Each people have their own opinion.", "Each person has their own opinion."),
            ("There was less people than expected.", "There were fewer people than expected."),
            ("I seen him yesterday.", "I saw him yesterday."),
            ("I must of left my keys at home.", "I must have left my keys at home."),
            ("Irregardless of the weather, we will go.", "Regardless of the weather, we will go."),
            ("The team are playing tonight.", "The team is playing tonight."),
            ("She done well on the test.", "She did well on the test."),
            ("Less students attended the class.", "Fewer students attended the class."),
            ("It's one of the only places left.", "It's one of the few places left."),
            ("I feel badly about it.", "I feel bad about it."),
            ("There's many ways to solve this.", "There are many ways to solve this."),
            ("The data shows interesting trends.", "The data show interesting trends."),
        ],
    },
    'Arithmetic': {
        'Easy': [
            ("What is 2 + 2?", "4"),
            ("What is 3 + 5?", "8"),
            ("What is 7 - 4?", "3"),
            ("What is 6 x 1?", "6"),
            ("What is 9 / 3?", "3"),
            ("What is 5 + 2?", "7"),
            ("What is 8 - 6?", "2"),
            ("What is 4 x 2?", "8"),
            ("What is 10 / 2?", "5"),
            ("What is 1 + 1?", "2"),
            ("What is 2 - 1?", "1"),
            ("What is 3 x 3?", "9"),
            ("What is 4 / 2?", "2"),
            ("What is 6 + 4?", "10"),
            ("What is 5 - 3?", "2"),
            ("What is 9 - 6?", "3"),
            ("What is 7 + 2?", "9"),
            ("What is 8 x 2?", "16"),
            ("What is 6 / 3?", "2"),
            ("What is 11 - 6?", "5"),
            ("What is 4 + 5?", "9"),
            ("What is 5 x 2?", "10"),
            ("What is 9 - 5?", "4"),
            ("What is 6 / 2?", "3"),
            ("What is 3 + 6?", "9"),
        ],
        'Intermediate': [
            ("What is 12 x 12?", "144"),
            ("What is 15 / 3?", "5"),
            ("What is 50 - 25?", "25"),
            ("What is 8 x 7?", "56"),
            ("What is 36 / 6?", "6"),
            ("What is 14 + 28?", "42"),
            ("What is 100 - 55?", "45"),
            ("What is 9 x 9?", "81"),
            ("What is 20 / 4?", "5"),
            ("What is 40 + 60?", "100"),
            ("What is 16 x 2?", "32"),
            ("What is 75 / 3?", "25"),
            ("What is 27 + 13?", "40"),
            ("What is 45 - 15?", "30"),
            ("What is 24 / 6?", "4"),
            ("What is 32 x 3?", "96"),
            ("What is 60 / 5?", "12"),
            ("What is 18 - 9?", "9"),
            ("What is 21 + 19?", "40"),
            ("What is 100 / 20?", "5"),
            ("What is 25 x 4?", "100"),
            ("What is 50 / 10?", "5"),
            ("What is 30 - 14?", "16"),
            ("What is 11 x 11?", "121"),
            ("What is 48 / 8?", "6"),
        ],
        'Advanced': [
            ("What is the square root of 144?", "12"),
            ("What is 123 x 3?", "369"),
            ("What is 1000 / 25?", "40"),
            ("What is 58 + 77?", "135"),
            ("What is 200 - 123?", "77"),
            ("What is 49 x 2?", "98"),
            ("What is 500 / 5?", "100"),
            ("What is 33 + 66?", "99"),
            ("What is 150 - 75?", "75"),
            ("What is the square root of 121?", "11"),
            ("What is 225 / 15?", "15"),
            ("What is 19 x 19?", "361"),
            ("What is 144 / 12?", "12"),
            ("What is 169 - 94?", "75"),
            ("What is 72 + 28?", "100"),
            ("What is 16 x 16?", "256"),
            ("What is 81 / 9?", "9"),
            ("What is 32 + 68?", "100"),
            ("What is 200 / 25?", "8"),
            ("What is 13 x 13?", "169"),
            ("What is 63 / 7?", "9"),
            ("What is 75 + 50?", "125"),
            ("What is 250 - 150?", "100"),
            ("What is 24 x 24?", "576"),
            ("What is 90 / 10?", "9"),
        ],
    }
}
